/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {

  public static void main(String[] args) {
    // Som intro idag skal me gå igjennom 3 ting
    // if og else statements
    // While løkker
    // Hvordan hente input fra konsoll og hvordan man skal skrive til konsoll
    

    // String høgre = "Høyre";
    // String Venstre = "Venstre";
    // 
    // //If setning
    // if (høgre.equals("Høyre")){
    //   System.out.println("Korrekt!");
    // } else {
    //   System.out.println("Feil!");
    // }
    // // If setning med negasjon
    // if (!Venstre.equals("Venstre")){
    //   System.out.println("Korrekt");
    // } else {
    //   System.out.println("Feil");
    // }
    // // If else setning
    // if (!høgre.equals("Høgre")){
    //   System.out.println("Korrekt");
    // } else if (Venstre.equals("Venstre")){
    //   System.out.println("Korrekt");
    // } else {
    //   System.out.println("Feil");
    // }
    
    //While løkke
    // boolean ferdig = false;
    // int i = 0;
    // while (ferdig == false){
    //     System.out.println(i);
    //     if (i == 10){
    //       ferdig = true;
    //     }
    // }
    //

    // Ta input fra bruker
    // Scanner brukerinput = new Scanner(System.in);
    // String input = brukerinput.nextLine();
    // System.out.println("Brukeren skrev: " + input);
    // brukerinput.close();
  }

}
