/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class Example{

  public static void main(String[] args) {
    // Boolean for hele spillet:)
    boolean doNotFinish = false;
    // Starter en scanner, dette lar brukerene skrive input
    Scanner scanner = new Scanner(System.in);
    // Variable for å lagre spillernavnet
    String playerName = null;
    // Boolean for å gå videre til neste spørsmål
    boolean nextQuestion = false;
    // Tom teksstreng for å lagre spilleren sitt valg
    String playerChoice = null;

    // Start spillet
    while (!doNotFinish) {

      while (!nextQuestion) {
        System.out.println("Skriv inn navnet ditt!");
        String input = scanner.nextLine();
        if (input.equals("exit")) {
          System.out.println("Ferdig");
          doNotFinish = true;
          nextQuestion = true;
        } else {
          playerName = input;
          System.out.println("Velkommen, " + playerName + "!");
          nextQuestion = true;
        }
      }

      // Reset for neste spørsmål
      nextQuestion = false;

      // Første spørsmål
      while (!nextQuestion) {
        //Skriv ut situasjonen
        System.out.println("Du står nå ved et veikryss. Du kan velge å gå enten til høyre eller til venstre. \n Til høyre står en trollman, han holder en tykk bok og stenger veien videre som går over inn innsjø \n Til venstre står et troll, det er ikke så stort og står og snakker med seg selv. \n Det vokter veien videre som går over en bro! \n Hva velger du? Skriv 'Høyre' for å gå til høyre og 'Venstre' for å gå til venstre");
        //Lagre inputet fra brukeren 
        playerChoice = scanner.nextLine();
        // Dersom brukeren valgte venstre
        if (playerChoice.toLowerCase().equals("venstre")) {
          //Skriv ut valget
          System.out.println("Du valgte Venstre og går nå mot trollmannen!");
          //Gjør klar for neste spørsmål
          nextQuestion = true;
        } else if (playerChoice.toLowerCase().equals("høyre")) {
          //Skriv ut valget
          System.out.println("Du valgte Trollet og går nå mot trollet!");
          // Gjør klar for neste spørsmål
          nextQuestion = true;
        } else {
          System.out.println("Ugyldig valg. Prøv igjen.");
        }
      }
      doNotFinish = true;
    }

    scanner.close();
  }

}
