/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class Example{

  public static void main(String[] args) {
    // Boolean for hele spillet:)
    boolean doNotFinish = false;
    // Starter en scanner, dette lar brukerene skrive input
    Scanner scanner = new Scanner(System.in);
    // Variable for å lagre spillernavnet
    String playerName = null;
    // Boolean for å gå videre til neste spørsmål
    boolean nextQuestion = false;
    // Tom teksstreng for å lagre spilleren sitt valg
    String playerChoice = null;

    // Start spillet
    while (!doNotFinish) {
    }

    scanner.close();
  }

}
